#spring.application.name=jpashop
#spring.output.ansi.enabled=ALWAYS

spring:
  output:
    ansi:
      enabled: ALWAYS
  datasource:
    url: jdbc:h2:tcp://localhost/~/Documents/dev/backend/jpashop
    username: sa
    password:
    # DB 연결을 위해 JDBC 드라이버의 클래스 이름을 지정함.
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      # 자동으로 table을 만들어주는 모드
      ddl-auto: create
    properties:
      hibernate:
        # show_sql: true -> system.out으로 로그를 찍음
        format_sql: true

logging:
  level:
    # 하이버네이트가 생성하는 SQL을 디버그 모드로 콘솔에 출력해줌 (Logger를 통해 찍어줌)
    org.hibernate.SQL: debug
